// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  caption_image: dynamic(() => import('./CaptionImage')),
  documentation: dynamic(() => import('./Documentation')),
  grid: dynamic(() => import('./Grid')),
  link_list: dynamic(() => import('./LinkList')),
  navigation_links: dynamic(() => import('./NavigationLinks')),
  rich_text: dynamic(() => import('./RichText')),
  video: dynamic(() => import('./Video')),
};
