---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stephaniegiorgis-secrets
  namespace: production
spec:
  encryptedData:
    RESEND_KEY: AgAi7WqNHQoJS7q8nLxNW0S0d0UeQGEVTiRZ88uXo1GEgyBO/Ou3YMe1hoQmPCP7Jgj+T8mUg4WXt39zNeczfl+pFoQOCO80hikbB4TNqaUQbeoQ+524BNBG83mnShUFRFCqCi5Uuc7SiByYPWLuYEP8w6dvJ7My1JeLaTj0E0cqSrZSlZWxTRU9xAjn6JC0dAfmEbc2H7699OYSEr2HwR/y6ogYlDdXQoP+xSPRCuAFk6sheJCNH7wC6P3vzAOoZJP3s7Dh1qyC+H46X+ePKLtYAbSWahmk6jUeR4bJuv2sLqKu4933jNu54M62BOTQHGpZn//cwBUj1LGMEx55dLSKk2lDwppf0YEZyMav/lMx7jgXrPeo440ZUaPbxtn7T/7LdlE9GHjZa3t5swSg1JgUW+h40oRo6fUzQ78OzckqasmKnCI4k//yTWqVbqucyohjVYaQEKg/9km0gsck2PpEJZHuMCdrPRIKjQNKqQYS1xOlFcGtEF7cgNYOktpM/u/pJED5AERu3IZhk3H3sZ+v2YiGCxDeTzolQ2oKjzSJbqG3jQdlpbYlhAOCRn8gVf8i2Pe/DR092s6Zn8WthtHLbtPbMzfmuyhEQlchufx3S+svoD0MBvcHCdAL5G3Ysx0e992qzIQUbarXw+uUf6ycfhxrdDH+VmfPnYRwwsqTdHiYmd/hn38hj8WrS7fUdiI3nyqLS8WfbRySNubjMe0c2GUXyGmYOxhmEn9UoexAhtMnOE0=
    REVALIDATE_SECRET: AgAl5C20+iVw+bD6fENzf9GzKXEdkcqZaaK7EtP3maq21kfFkdrKrQfUQOUk+lu5F4A1sHqsgmbTt/Twv7CvfPd8P9D9MEDnx0Fhf69q/Re9cqkw2H4wpAHPKPUg6o+y3Ce6UgfZgyompN9xj6J8/Wi4x9NS272mrR/qVvL7Sf1Rvya0H8E29GQhtXeBhIV6BYGQGUj1cx/woEWSNSAMuJjLhY5Zoaa+qok5oWHw+Q0oxKpqSaekKddKXdjUeaQ1//ddOFAo5HQoc+ozd2J61mSA6sjs6q4QbGHd6HOq5ou0ibHqXRJujwMadhXrQ5mcm/KSKYXcbyQQzEBhAb/qwH7mO7LcyWNPvEzbh9NbxAoNrwTM6NNJrd+nAacKr8TWS2dlP2J4XXCwrx6J6l4+Kz/zYA/48ZjovPBQpGtnwwFZhRSrCIxdpCYctLGJv/bOUPPLOy1MsqZB92ZyjDDXXUSqkcYZAEQmBkvvMMBGrGj6SKJTE4cHqRJCP74XPYu7BXCcFBI18PqIwmZZPCNDbe6NpbLGT1B/cLRoLjlHOaDwaNaLlSGzOAgNWttZ5XJ/M14Dbs0kNYzhXmqY8qRVxoozXrW5uqtv99Yhglh6HhI6ze0aaHjHnygzYMRhlVA0fq8M2QX9TZ34V+RE12ezAgUjvc7OVEi8So90LLsupB3xJghUETMn4hVOHA7RmcAsgRer4xZJ/isAY0X2Xgx1XUWY
  template:
    metadata:
      name: stephaniegiorgis-secrets
      namespace: production
