---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stephaniegiorgis-secrets
  namespace: staging
spec:
  encryptedData:
    RESEND_KEY: AgB48IrAftmI/gJG5sIibPukvKimZeWYroUSH5z4pFcRNtACPoxHHtTbaZ4/+kIFqQfXfHUL2Q61mnGfbCWS/09cdgaRx0ZllqVoGBO2TG/gKQhWpycmu74O311MTPnr2PiQx0jt+nc0qG1XbfWOD5e8mO6HLqCNmRK0bq2IZsDptT/8Joz+nKvf96fEHWwC+fE9C4z5jOxRi2sgHa5CiSv5f89CEnTB3aFcmxFGtGWIAmqJ94dBYWh6Lob5u7BrR6ds3Jx15gpAgayw7gak1lAjW3RiiQWBHBRgpVhXIHrsXkE6zv0hlDLZvfTd1PWyS3gVP6HOfWxkfkA3y+r375Rn67DHkuQk7gRgiYEZmI7Y0GV8hm9ugDTS7J7Xm8IsK9v9H2LWxnCCu4FX1jdkFi4N7/oBSSi9Kk443wl0qKpnN4DoNPT1YkhtXyPzwi7qAhzEeX89jCIrOM7AdC8jc1n0/mf8+fBovGjFAIE4Sf7fmQ1K09k8Wgmj+7KGKhsxo26oBjkptxBfYQ/oCBbQwe1bMc28TJxCW7YK9HAGLbWQVeVvswpviZeuqxkFqcBye0/Pl4vTQmJ+XJS19f5HcVhWmAiWbkVzKwRLW0vN+thk1XX7LiqDqMRI/mWLgbwmOSU2+9xPggB/men9DlBBDgqGrwUJSGYD/7xX5ZXcsFsPiaPsYc/WCxVnbP9K4C5vDc2Q84t51T15YajW7XrnujB+6TcLjkmKzwTAlK57hNxG2HxZCEI=
    REVALIDATE_SECRET: AgCCgKLKrquJsEpT8gBVgH6RpcgqTZ6Ef7QOMF3RkThyBsIz+QxEJAjVE8n2YoHHYdB7V2ORyU/aGOutxDoqkdXGs8rktiTpUp4bG7xdjEesn/1NESU8QgdPQmzOGYQWhEOQdGmtqtW+QCLKp0G7PdLeXdxt/XDETtQoo7a1Z04nVX23rYnIaqIzX7jEUGpUXNxNrYj+/oY8TfpPFtLzn9lEgLkDP8/hlEO141uOo3czQzK4wKndwYkfT5Yp5H+mdEnJVN7CU/qWlNlMIgiMDWuuUQ80//yGZjUUPbqwHMTBzSpi7vq0C2LQ56PW9+QKpprROkbgCV5Wat27jEXNn5krPEk17A8hulHNARD8xrxIcO3yuuI2SNP2xz64+BtWw7lWezHOg66NLrUuKxyTsN77XPuo7N517YJQprW8lcnsQte2SoZNQ8HOrMntbznpRsuHa4UX8I4RxhMgdvLx4e+DKK9Ss9bbwiTfXHTfj/lHN8RVHtoB9yzeQSdoQ9VLF+P5wOp6XcGvr67Ry6sjxmbZvJdzEaD3wLFzb5CrWO9maqKPtOYz/VmZGOCGPFYv+ivbpEX90t/H3Ie7ntIojSlBe0sxBVyyvJlSRvbMB2Cz3ntwwMpnVQckQe1JK/sObalVegxFxJXn+X6kmfxTt4hp5qIXrA7R6/p6ehPXgt0ZWUcoQkOFrPQsBKc/lEut/T8AcDPE8G0LfCGUzf+YRRZ3
  template:
    metadata:
      name: stephaniegiorgis-secrets
      namespace: staging
